import 'dotenv/config'
import { argv } from 'node:process'
import { promisify } from 'node:util'

import { exec as exec_unpromised } from 'node:child_process'

import { readFile as readFile_unpromised } from 'node:fs'

import { JSDOM } from 'jsdom'

let exec = promisify(exec_unpromised);
let readFile = promisify(readFile_unpromised);

if (argv[2] == undefined) {
    throw Error("Didn't pass in website. Do node start -- https://example.com");
}

const website = argv[2];

const { stdout, stderr } = await download_website_with_httrack(website);

// Remove the https:// from beginning
const website_without_http = website.slice(8);

const index_file = `./HTTrack-website-downloads/${website_without_http}index.html`;

const data = await readFile(index_file, 'utf8');

const { window: { document: website_document } } = new JSDOM(data);

website_document.querySelectorAll("img").forEach(img => {
    img.removeAttribute("srcset");
    if (img.alt == "") {
        img.alt = "This should be generated by gpt";
    }
    console.log(img.outerHTML);
})

async function download_website_with_httrack(website) {
    console.log(`Downloading ${website}`);
    const { stdout, stderr } = await exec(`mkdir -p HTTrack-website-downloads && rm -rf "./HTTrack-website-downloads/*" && cd HTTrack-website-downloads && httrack ${website} +* -r2`);

    console.log(stdout);
    console.log(stderr);
}
