import 'dotenv/config'
import { argv } from 'node:process'
import { promisify } from 'node:util'

import { exec as exec_unpromised } from 'node:child_process'

import { readFile, writeFile } from 'node:fs/promises'

import { JSDOM } from 'jsdom'

let exec = promisify(exec_unpromised);

if (argv[2] == undefined) {
    throw Error("Didn't pass in website. Do node start -- https://example.com");
}

const website = argv[2];

// const { stdout, stderr } = await download_website_with_httrack(website);

// Remove the https:// from beginning
const website_without_http = website.slice(8);
const index_file_path = `./HTTrack-website-downloads/${website_without_http}index.html`;

const index_file = await readFile(index_file_path, 'utf8');
const { window: { document: website_document } } = new JSDOM(index_file);

console.log("Copying website download and generating alt text...");
website_document.querySelectorAll("img").forEach(img => {
    // Need to remove the srcset from images--we only have just the src image from the download
    img.removeAttribute("srcset");
    if (img.alt == "") {
        img.alt = "This should be generated by gpt";
    }
})

// Copy the website download and modify the copy
await exec(`rm -rf HTTrack-modified && cp -r HTTrack-website-downloads HTTrack-modified`);

// Write the index with the new alt text
const copied_index_file_path = `./HTTrack-modified/${website_without_http}index.html`;
await writeFile(copied_index_file_path, website_document.querySelector(":root").outerHTML);

async function download_website_with_httrack(website) {
    console.log(`Downloading ${website}`);
    const { stdout, stderr } = await exec(`mkdir -p HTTrack-website-downloads && rm -rf "./HTTrack-website-downloads/*" && cd HTTrack-website-downloads && httrack ${website} +* -r2`);

    console.log(stdout);
    console.log(stderr);
}
