import 'dotenv/config'
import { argv } from 'node:process'
import { promisify } from 'node:util'
import { exec as exec_unpromised } from 'node:child_process'
import { readFile, writeFile } from 'node:fs/promises'
import { JSDOM } from 'jsdom'
import puppeteer from 'puppeteer-core'

let exec = promisify(exec_unpromised);

if (argv[2] == undefined) {
    throw Error("Didn't pass in website. Do node start -- https://example.com");
}

const website = argv[2];

// const { stdout, stderr } = await download_website_with_httrack(website);

// Remove the https:// from beginning
const website_without_http = website.slice(8);
const index_file_path = `./HTTrack-website-downloads/${website_without_http}index.html`;

const index_file = await readFile(index_file_path, 'utf8');
const { window: { document: website_document } } = new JSDOM(index_file);

console.log("Copying website download and generating alt text...");
website_document.querySelectorAll("img").forEach(img => {
    // Need to remove the srcset from images--we only have just the src image from the download
    img.removeAttribute("srcset");

    // Removes "loading=lazy" from images so they show up in pdfs
    img.removeAttribute("loading");
    if (img.alt == "") {
        img.alt = "This should be generated by gpt";
    }
})

// Copy the website download and modify the copy
await exec(`rm -rf HTTrack-modified && cp -r HTTrack-website-downloads HTTrack-modified`);

// Write the index with the new alt text
const copied_index_file_path = `./HTTrack-modified/${website_without_http}index.html`;
await writeFile(copied_index_file_path, website_document.querySelector(":root").outerHTML);

console.log("Taking a pdf of the site");
const browser = await puppeteer.launch({ executablePath: '/home/apple/.nix-profile/bin/google-chrome-stable' });
const page = await browser.newPage();

const url = `${process.cwd()}/HTTrack-modified/${website_without_http}index.html`;
await page.goto(`file:///${process.cwd()}/HTTrack-modified/${website_without_http}index.html`);

await exec(`mkdir -p ./website-as-pdf/${website_without_http}`);

await page.pdf({
    path: `./website-as-pdf/${website_without_http}index.pdf`,
});

console.log("Pdf is now at " + `./website-as-pdf/${website_without_http}index.pdf`);

await browser.close();

async function download_website_with_httrack(website) {
    console.log(`Downloading ${website}`);
    const { stdout, stderr } = await exec(`mkdir -p HTTrack-website-downloads && rm -rf "./HTTrack-website-downloads/*" && cd HTTrack-website-downloads && httrack ${website} +* -r2`);

    console.log(stdout);
    console.log(stderr);
}
